version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitProject1Project
  gitServerName: GH_SK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
- name: WmB2BDocuments
  version: "1.0"
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.gitproject1.integrations:TEST1
  packages:
  - name: GitProject1Project
    version: "1.0"
  - name: WmB2BDocuments
    version: "1.0"
- serviceName: wm.b2b.edi:convertToValues
  packages:
  - name: WmEDI
    version: 9.12.0.0.309
