version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitProject1Project
  gitServerName: GH_SK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
- name: WmB2BDocuments
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
